name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  CI:
    strategy:
      matrix:
        config:
          - {tag: 'ubuntu22.04', dockerfile: 'docker/ubuntu22.04.dockerfile'}
          - {tag: 'fedora38_mingw', dockerfile: 'docker/fedora38_mingw.dockerfile'}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker images
        uses: docker/build-push-action@v5
        with:
          tags: lammps/buildenv:${{ matrix.config.tag }}
          file: ${{ matrix.config.dockerfile }}
          build-args: ${{ matrix.config.build_args }}
          context: docker/
          push: ${{ github.event_name == 'push' ||  github.event_name == 'schedule' }}
