name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '0 1 * * FRI'

jobs:
  CI:
    strategy:
      matrix:
        config:
          - {tag: 'ubuntu18.04', dockerfile: 'docker/ubuntu18.04.dockerfile'}
          - {tag: 'ubuntu18.04_devcontainer', dockerfile: 'docker/ubuntu18.04_devcontainer.dockerfile'}
          - {tag: 'centos7', dockerfile: 'docker/centos7.dockerfile'}
          - {tag: 'fedora32_mingw', dockerfile: 'docker/fedora32_mingw.dockerfile'}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          repository: lammps/buildenv
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: ${{ matrix.config.tag }}
          dockerfile: ${{ matrix.config.dockerfile }}
          build_args: ${{ matrix.config.build_args }}
          path: docker/
          push: ${{ github.event_name == 'push' ||  github.event_name == 'schedule' }}
